<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "faoliyat".
 *
 * @property int $id
 * @property string|null $title_ru
 * @property string|null $title_uz
 * @property string|null $title_en
 * @property string|null $photo
 * @property string|null $file
 * @property int|null $category_id
 * @property string|null $description_ru
 * @property string|null $description_uz
 * @property string|null $description_en
 * @property int $status
 */
class Faoliyat extends \yii\db\ActiveRecord
{
    public $image;
    public $file;
    public $file1;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'faoliyat';
    }

    /**
     * {@inheritdoc}
     */
    public function afterDelete()
    {
        if ($this->file !== null && !empty($this->file)) {
            unlink(Yii::getAlias('@frontend').'/web/uploads/faoliyat/' . $this->file);
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['category_id', 'status'], 'integer'],
            [['description_ru', 'description_uz', 'description_en'], 'string'],
            [['title_ru', 'title_uz', 'title_en', 'photo', 'file'], 'string', 'max' => 255],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, bmp'],
            [['file1'], 'file', 'skipOnEmpty' => false, 'extensions' => 'doc, docx, xls, xlsx, pdf']

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title_ru' => Yii::t('app', 'Title Ru'),
            'title_uz' => Yii::t('app', 'Title Uz'),
            'title_en' => Yii::t('app', 'Title En'),
            'photo' => Yii::t('app', 'Photo'),
            'file' => Yii::t('app', 'File'),
            'category_id' => Yii::t('app', 'Category ID'),
            'description_ru' => Yii::t('app', 'Description Ru'),
            'description_uz' => Yii::t('app', 'Description Uz'),
            'description_en' => Yii::t('app', 'Description En'),
            'status' => Yii::t('app', 'Status'),
        ];
    }
    public function updateModel($new=false){

        $post = Yii::$app->request->post();

        if($this->load($post) ) {

            if( $new ){ // если создается только один раз при создании
                //$this->date = time();
            }
            if( !$this->save() ){
                Yii::$app->session->setFlash('info-error','Ошибка при сохранении!');
                print_r($this->getErrors());
                exit;

                return true;
            }

            Yii::$app->session->setFlash('info-success',' успешно сохранена!');

            return true;
        }
        return false;

    }
    public function upload()
    {
        if ($this->validate()) {
            $name = Yii::$app->security->generateRandomString(10) . '.' . $this->image->extension;
            $name1 = Yii::$app->security->generateRandomString(10) . '.' . $this->file1->extension;

            if ($this->photo !== null && !empty($this->photo)) {
                unlink(Yii::getAlias('@frontend').'/web/uploads/faoliyat/' . $this->photo);
            }
            if ($this->file !== null && !empty($this->file)) {
                unlink(Yii::getAlias('@frontend').'/web/uploads/faoliyat/' . $this->file);
            }
            $this->photo = $name;
            $this->file = $name1;
            $this->image->saveAs(Yii::getAlias('@frontend').'/web/uploads/faoliyat/' . $name);
            $this->file1->saveAs(Yii::getAlias('@frontend').'/web/uploads/faoliyat/' . $name1);
            return true;
        } else {
            return false;
        }
    }
    public function getCategory()
    {
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }
}
